module.exports = {
  siteName:'ShiningPage',

  googleAds: true,

  // serverURL: 'http://localhost:4200',
  serverURL: 'https://api.shiningpage.com',

  netAPIKey: 'dd12f93b99e6a599aa40cb690a38b643',

  noIndexPages: [
    'login',
    'register',
    'contact',
    'dashboard',
    'tos',
    'privacy',
    'disclaimer',
    'projects',
    'ruby',
    'booking',
    'chatList',
    'notification',
    'page404',
    'reviews',
    'user'
  ],

  socialTopics: {
    instagram: "Instagram",
    youtube: "Youtube",
    facebook: "Facebook",
    twitter: "X",
    tiktok: "TikTok",
    linkedin: "Linkedin",
    telegram: "Telegram",
    traffic: "Traffic",
    discord: "Discord",
    snapchat: "Snapchat",
    twitch: "Twitch",
    spotify: "Spotify",
    // google: "Google",
    // review: "Review",
  },

  s: 825,
  NavH: 60,
  langArray: ['fa', 'en', 'ar', ''],
  //subNavH: 70,
  headerColor1: '#000000',
  headerColor2: '#5b5bff',
  totalBorder: '#9e5dff80',
  listRefreshQty: 9,
  listRefreshQtyBig: 50,
  listRefreshQtySmall: 10,
  adsSpace: 20,

  copyRightText: '2024 All Rights Reserved',
  sideBlackIcon: [4, 11],
  lightColors: [0, 4, 9, 10, 11, 12, 13, 14, 22, 25, 42, 54, ],
  designedByColors: [0, 2, 3, 4, 9, 10, 11, 12, 13, 14, 16, 22, 24, 25, 38, 41, 49, 52],
  colors: {
    C0: '#BAC4D4',
    C1: '#364CFF',
    C2: '#24b735',
    C3: '#FF9547',
    C4: '#ede557',
    C5: '#B246D4',
    C6: '#824400',
    C7: '#000000',
    C8: '#ff002e',
    C9: '#f8cb71',
    C10: '#fd90e0',
    C11: '#ffffff',
    C12: '#00ddff',
    C13: '#77787A',
    C14: '#D1A449',
    C15: '#00194c',
    C16: '#D8A9A4',
    C17: '#0c5b14',
    C18: '#FC0496',
    C19: '#ff34a3',
    C20: '#8F1657',
    C21: '#541a67',
    C22: '#BAC4D4',
    C23: '#CE0301',
    C24: '#d5cc95',
    C25: '#99E315',
    C26: '#555555',
    C27: '#1c9328',
    C28: '#601C3B',
    C29: '#B24C31',
    C30: '#1c9328',
    C31: '#D1A449',
    C32: '#D1A449',
    C33: '#555555',
    C34: '#364CFF',
    C35: '#00BFDD',
    C36: '#B246D4',
    C37: '#c40020',
    C38: '#D1A449',
    C39: '#ff34a3',
    C40: '#000000',
    C41: '#24b735',
    C42: '#F4D011',
    C43: '#602909',
    C44: '#af011e',
    C45: '#24b735',
    C46: '#B246D4',
    C47: '#259FB4',
    C48: '#F81550',
    C49: '#00b0cb',
    C50: '#835965',
    C51: '#1079B8',
    C52: '#9D8361',
    C53: '#000000',
    C54: '#FBD8D0',
    C55: '#9564F7',
    C56: '#D1A449',
    C57: '#721119',
    C58: '#af011e',

  },
  mapColors: {
    C0: '#9aa7ba',
    C1: '#364CFF',
    C2: '#24b735',
    C3: '#FF9547',
    C4: '#f4ef5f',
    C5: '#B246D4',
    C6: '#824400',
    C7: '#000000',
    C8: '#ff002e',
    C9: '#f8cb71',
    C10: '#fd90e0',
    C11: '#555555',
    C12: '#00ddff',
    C13: '#555555',
    C14: '#D1A449',
    C15: '#00194c',
    C16: '#D8A9A4',
    C17: '#0c5b14',
    C18: '#FC0496',
    C19: '#ff34a3',
    C20: '#8F1657',
    C21: '#541a67',
    C22: '#555555',
    C23: '#CE0301',
    C24: '#c40020',
    C25: '#99E315',
    C26: '#555555',
    C27: '#1c9328',
    C28: '#601C3B',
    C29: '#B24C31',
    C30: '#1c9328',
    C31: '#B97F15',
    C32: '#B97F15',
    C33: '#555555',
    C34: '#364CFF',
    C35: '#00b0cb',
    C36: '#B246D4',
    C37: '#c40020',
    C38: '#D1A449',
    C39: '#d42e89',
    C40: '#000000',
    C41: '#24b735',
    C42: '#fed400',
    C43: '#602909',
    C44: '#c40020',
    C45: '#24b735',
    C46: '#B246D4',
    C47: '#10879c',
    C48: '#F81550',
    C49: '#00b0cb',
    C50: '#B58B97',
    C51: '#1079B8',
    C52: '#876d4e',
    C53: '#000000',
    C54: '#ca8e81',
    C55: '#9564F7',
    C56: '#ab7e22',
    C57: '#721119',
    C58: '#c40020',

  },
  categories: [ // index مهم است و نباید حذف شود چون در جدول های مختلف دیتابیس ذخیره شده است
    { index: 10, title: 'beautyHealthWellness' },
    { index: 2, title: 'buildingServices' },
    { index: 8, title: 'cleaningServices' },
    { index: 1, title: 'foodStuffs' },
    // { index: 3, title: 'industrialToolsEquipment' },
    // { index: 4, title: 'carSparePartsAccessories' },
    // { index: 5, title: 'digitalProductsAccessories' },
    // { index: 6, title: 'goldJewelryOrnaments' },
    // { index: 7, title: 'clothing' },
    { index: 9, title: 'homeKitchenAppliances' },
    // { index: 11, title: 'booksStationery' },
    // { index: 12, title: 'gameEntertainment' },
    { index: 13, title: 'artHandicraft' },
    // { index: 14, title: 'officeSupplies' },
    { index: 15, title: 'sportsRecreationalEquipment' },
    // { index: 16, title: 'petsAccessories' },
    { index: 17, title: 'trainingServices' },
    { index: 18, title: 'other' }
  ],

  loadingBar: {
    height: 10,
    color:'linear-gradient(to right , #db5bff, #f2e489)',
    //color:'linear-gradient(to left, yellow, orange, red, green, blue, indigo, violet)',
    L0: '#BAC4D4',
    L1: '#364CFF',
    L2: '#4CD45D',
    L3: '#FF9547',
    L4: '#f2e489',
    L5: '#B246D4',
    L6: '#824400',
    L7: '#000000',
    L8: '#ff002e',
    L9: '#D4A443',
    L10: '#FD90E0',
    L11: '#ffffff',
    L12: '#00BFDD',
    L13: '#77787A',
    L14: '#D1A449',
    L15: '#00194c',
    L16: '#D8A9A4'
  },

  psyCard: {
      width: 250,
      subWidth: 260,
      cardBackColor1:'#ffffff',
      cardBackColor2:'#5b5bff',
  },

  greenLine: 5,
  redLine: -5,

  Lp1:5,
  Lp2:2.5,
  Lp3:-2.5,
  Lp4:-5,

  L1:250,
  L2:150,
  L3:-150,
  L4:-250,

  chart: {
      fontColor: '#000000',
      backColor: '#ffffff99',
      gridLinesColor: '#ededed90',
      zeroLineColor: '#999999',
      color0: '#31BA0D80',
      color1: '#9966ff80',
      color2: '#36a2eb80',
      color3: '#ffce5680',
      color4: '#ff9f4080',
      color5: '#ff638480',
      color6: '#ff000080',
      border0: '#31BA0D',
      border1: '#9966ff',
      border2: '#36a2eb',
      border3: '#ffce56',
      border4: '#ff9f40',
      border5: '#ff6384',
      border6: '#ff0000',
  },

  subChart: {
      fontColor: '#000000',
      backColor: '#ffffff',
      gridLinesColor: '#ededed',
      zeroLineColor: '#999999',
      color1: 'rgba(153, 102, 255, 1)',
      color2: 'rgba(54, 162, 235, 1)',
      color3: 'rgba(255, 206, 86, 1)',
      color4: 'rgba(255, 159, 64, 1)',
      color5: 'rgba(255,99,132,1)',
      border1: 'rgba(153, 102, 255, 1)',
      border2: 'rgba(54, 162, 235, 1)',
      border3: 'rgba(255, 206, 86, 1)',
      border4: 'rgba(255, 159, 64, 1)',
      border5: 'rgba(255,99,132,1)',
  },

      // chart: {
  //     fontColor: '#FDF9EF',
  //     backColor: '#000000',
  //     gridLinesColor: '#191919',
  //     zeroLineColor: '#616161',
  //     color0: '#31BA0D20',
  //     color1: 'rgba(153, 102, 255, 0.2)',
  //     color2: 'rgba(54, 162, 235, 0.2)',
  //     color3: 'rgba(255, 206, 86, 0.2)',
  //     color4: 'rgba(255, 159, 64, 0.2)',
  //     color5: 'rgba(255,99,132,0.2)',
  //     color6: '#ff000020',
  //     border0: '#31BA0D',
  //     border1: 'rgba(153, 102, 255, 1)',
  //     border2: 'rgba(54, 162, 235, 1)',
  //     border3: 'rgba(255, 206, 86, 1)',
  //     border4: 'rgba(255, 159, 64, 1)',
  //     border5: 'rgba(255,99,132,1)',
  //     border6: '#ff0000',
  // },

  // subChart: {
  //     fontColor: '#ffffff',
  //     backColor: '#00358C',
  //     gridLinesColor: '#19468e',
  //     zeroLineColor: '#1a6cef',
  //     color1: 'rgba(153, 102, 255, 1)',
  //     color2: 'rgba(54, 162, 235, 1)',
  //     color3: 'rgba(255, 206, 86, 1)',
  //     color4: 'rgba(255, 159, 64, 1)',
  //     color5: 'rgba(255,99,132,1)',
  //     border1: 'rgba(153, 102, 255, 1)',
  //     border2: 'rgba(54, 162, 235, 1)',
  //     border3: 'rgba(255, 206, 86, 1)',
  //     border4: 'rgba(255, 159, 64, 1)',
  //     border5: 'rgba(255,99,132,1)',
  // },

  countryArr: [
      {
        "code": "AF",
        "country": "Afghanistan",
        "continent": "Asia",
      },
      {
        "code": "AX",
        "country": "Aland Islands",
        "continent": "Europe",
      },
      {
        "code": "AL",
        "country": "Albania",
        "continent": "Europe",
      },
      {
        "code": "DZ",
        "country": "Algeria",
        "continent": "Africa",
      },
      {
        "code": "AS",
        "country": "American Samoa",
        "continent": "Oceania",
      },
      {
        "code": "AD",
        "country": "Andorra",
        "continent": "Europe",
      },
      {
        "code": "AO",
        "country": "Angola",
        "continent": "Africa",
      },
      {
        "code": "AI",
        "country": "Anguilla",
        "continent": "North America",
      },
      {
        "code": "AQ",
        "country": "Antarctica",
        "continent": "Antartica",
      },
      {
        "code": "AG",
        "country": "Antigua and Barbuda",
        "continent": "North America",
      },
      {
        "code": "AR",
        "country": "Argentina",
        "continent": "South America",
      },
      {
        "code": "AM",
        "country": "Armenia",
        "continent": "Asia",
      },
      {
        "code": "AW",
        "country": "Aruba",
        "continent": "North America",
      },
      {
        "code": "AU",
        "country": "Australia",
        "continent": "Oceania",
      },
      {
        "code": "AT",
        "country": "Austria",
        "continent": "Europe",
      },
      {
        "code": "AZ",
        "country": "Azerbaijan",
        "continent": "Asia",
      },
      {
        "code": "BS",
        "country": "Bahamas",
        "continent": "North America",
      },
      {
        "code": "BH",
        "country": "Bahrain",
        "continent": "Asia",
      },
      {
        "code": "BD",
        "country": "Bangladesh",
        "continent": "Asia",
      },
      {
        "code": "BB",
        "country": "Barbados",
        "continent": "North America",
      },
      {
        "code": "BY",
        "country": "Belarus",
        "continent": "Europe",
      },
      {
        "code": "BE",
        "country": "Belgium",
        "continent": "Europe",
      },
      {
        "code": "BZ",
        "country": "Belize",
        "continent": "North America",
      },
      {
        "code": "BJ",
        "country": "Benin",
        "continent": "Africa",
      },
      {
        "code": "BM",
        "country": "Bermuda",
        "continent": "North America",
      },
      {
        "code": "BT",
        "country": "Bhutan",
        "continent": "Asia",
      },
      {
        "code": "BO",
        "country": "Bolivia",
        "continent": "South America",
      },
      {
        "code": "BQ",
        "country": "Bonaire/Eust",
        "continent": "North America",
      },
      {
        "code": "BA",
        "country": "Bosnia Herzg",
        "continent": "Europe",
      },
      {
        "code": "BW",
        "country": "Botswana",
        "continent": "Africa",
      },
      {
        "code": "BV",
        "country": "Bouvet Island",
        "continent": "Antartica",
      },
      {
        "code": "BR",
        "country": "Brazil",
        "continent": "South America",
      },
      {
        "code": "IO",
        "country": "Br Ind Oc Tr",
        "continent": "Asia",
      },
      {
        "code": "BN",
        "country": "Brunei",
        "continent": "Asia",
      },
      {
        "code": "BG",
        "country": "Bulgaria",
        "continent": "Europe",
      },
      {
        "code": "BF",
        "country": "Burkina Faso",
        "continent": "Africa",
      },
      {
        "code": "BI",
        "country": "Burundi",
        "continent": "Africa",
      },
      {
        "code": "CV",
        "country": "Cabo Verde",
        "continent": "Africa",
      },
      {
        "code": "KH",
        "country": "Cambodia",
        "continent": "Asia",
      },
      {
        "code": "CM",
        "country": "Cameroon",
        "continent": "Africa",
      },
      {
        "code": "CA",
        "country": "Canada",
        "continent": "North America",
      },
      {
        "code": "KY",
        "country": "Cayman Islands",
        "continent": "North America",
      },
      {
        "code": "CF",
        "country": "Central African",
        "continent": "Africa",
      },
      {
        "code": "TD",
        "country": "Chad",
        "continent": "Africa",
      },
      {
        "code": "CL",
        "country": "Chile",
        "continent": "South America",
      },
      {
        "code": "CN",
        "country": "China",
        "continent": "Asia",
      },
      {
        "code": "CX",
        "country": "Christmas Island",
        "continent": "Asia",
      },
      {
        "code": "CC",
        "country": "Cocos Islands",
        "continent": "Asia",
      },
      {
        "code": "CO",
        "country": "Colombia",
        "continent": "South America",
      },
      {
        "code": "KM",
        "country": "Comoros",
        "continent": "Africa",
      },
      {
        "code": "CG",
        "country": "Congo",
        "continent": "Africa",
      },
      {
        "code": "CD",
        "country": "Congo",
        "continent": "Africa",
      },
      {
        "code": "CK",
        "country": "Cook Islands",
        "continent": "Oceania",
      },
      {
        "code": "CR",
        "country": "Costa Rica",
        "continent": "North America",
      },
      {
        "code": "HR",
        "country": "Croatia",
        "continent": "Europe",
      },
      {
        "code": "CU",
        "country": "Cuba",
        "continent": "North America",
      },
      {
        "code": "CW",
        "country": "Curaçao",
        "continent": "North America",
      },
      {
        "code": "CY",
        "country": "Cyprus",
        "continent": "Asia",
      },
      {
        "code": "CZ",
        "country": "Czechia",
        "continent": "Europe",
      },
      {
        "code": "CI",
        "country": "Côte d'Ivoire",
        "continent": "Africa",
      },
      {
        "code": "DK",
        "country": "Denmark",
        "continent": "Europe",
      },
      {
        "code": "DJ",
        "country": "Djibouti",
        "continent": "Africa",
      },
      {
        "code": "DM",
        "country": "Dominica",
        "continent": "North America",
      },
      {
        "code": "DO",
        "country": "Dominican",
        "continent": "North America",
      },
      {
        "code": "EC",
        "country": "Ecuador",
        "continent": "South America",
      },
      {
        "code": "EG",
        "country": "Egypt",
        "continent": "Africa",
      },
      {
        "code": "SV",
        "country": "El Salvador",
        "continent": "North America",
      },
      {
        "code": "GQ",
        "country": "Equatorial Guinea",
        "continent": "Africa",
      },
      {
        "code": "ER",
        "country": "Eritrea",
        "continent": "Africa",
      },
      {
        "code": "EE",
        "country": "Estonia",
        "continent": "Europe",
      },
      {
        "code": "SZ",
        "country": "Eswatini",
        "continent": "Africa",
      },
      {
        "code": "ET",
        "country": "Ethiopia",
        "continent": "Africa",
      },
      {
        "code": "FK",
        "country": "Falkland Islands",
        "continent": "South America",
      },
      {
        "code": "FO",
        "country": "Faroe Islands",
        "continent": "Europe",
      },
      {
        "code": "FJ",
        "country": "Fiji",
        "continent": "Oceania",
      },
      {
        "code": "FI",
        "country": "Finland",
        "continent": "Europe",
      },
      {
        "code": "FR",
        "country": "France",
        "continent": "Europe",
      },
      {
        "code": "GF",
        "country": "French Guiana",
        "continent": "South America",
      },
      {
        "code": "PF",
        "country": "French Polynesia",
        "continent": "Oceania",
      },
      {
        "code": "TF",
        "country": "French SRN TERR",
        "continent": "Antartica",
      },
      {
        "code": "GA",
        "country": "Gabon",
        "continent": "Africa",
      },
      {
        "code": "GM",
        "country": "Gambia",
        "continent": "Africa",
      },
      {
        "code": "GE",
        "country": "Georgia",
        "continent": "Asia",
      },
      {
        "code": "DE",
        "country": "Germany",
        "continent": "Europe",
      },
      {
        "code": "GH",
        "country": "Ghana",
        "continent": "Africa",
      },
      {
        "code": "GI",
        "country": "Gibraltar",
        "continent": "Europe",
      },
      {
        "code": "GR",
        "country": "Greece",
        "continent": "Europe",
      },
      {
        "code": "GL",
        "country": "Greenland",
        "continent": "North America",
      },
      {
        "code": "GD",
        "country": "Grenada",
        "continent": "North America",
      },
      {
        "code": "GP",
        "country": "Guadeloupe",
        "continent": "North America",
      },
      {
        "code": "GU",
        "country": "Guam",
        "continent": "Oceania",
      },
      {
        "code": "GT",
        "country": "Guatemala",
        "continent": "North America",
      },
      {
        "code": "GG",
        "country": "Guernsey",
        "continent": "Europe",
      },
      {
        "code": "GN",
        "country": "Guinea",
        "continent": "Africa",
      },
      {
        "code": "GW",
        "country": "Guinea-Bissau",
        "continent": "Africa",
      },
      {
        "code": "GY",
        "country": "Guyana",
        "continent": "South America",
      },
      {
        "code": "HT",
        "country": "Haiti",
        "continent": "North America",
      },
      {
        "code": "HM",
        "country": "Heard McDonald Isl",
        "continent": "Antartica",
      },
      {
        "code": "VA",
        "country": "Holy See",
        "continent": "Europe",
      },
      {
        "code": "HN",
        "country": "Honduras",
        "continent": "North America",
      },
      {
        "code": "HK",
        "country": "Hong Kong",
        "continent": "Asia",
      },
      {
        "code": "HU",
        "country": "Hungary",
        "continent": "Europe",
      },
      {
        "code": "IS",
        "country": "Iceland",
        "continent": "Europe",
      },
      {
        "code": "IN",
        "country": "India",
        "continent": "Asia",
      },
      {
        "code": "ID",
        "country": "Indonesia",
        "continent": "Asia",
      },
      {
        "code": "IR",
        "country": "Iran",
        "continent": "Asia",
      },
      {
        "code": "IQ",
        "country": "Iraq",
        "continent": "Asia",
      },
      {
        "code": "IE",
        "country": "Ireland",
        "continent": "Europe",
      },
      {
        "code": "IM",
        "country": "Isle of Man",
        "continent": "Europe",
      },
      {
        "code": "IL",
        "country": "Israel",
        "continent": "Asia",
      },
      {
        "code": "IT",
        "country": "Italy",
        "continent": "Europe",
      },
      {
        "code": "JM",
        "country": "Jamaica",
        "continent": "North America",
      },
      {
        "code": "JP",
        "country": "Japan",
        "continent": "Asia",
      },
      {
        "code": "JE",
        "country": "Jersey",
        "continent": "Europe",
      },
      {
        "code": "JO",
        "country": "Jordan",
        "continent": "Asia",
      },
      {
        "code": "KZ",
        "country": "Kazakhstan",
        "continent": "Asia",
      },
      {
        "code": "KE",
        "country": "Kenya",
        "continent": "Africa",
      },
      {
        "code": "KI",
        "country": "Kiribati",
        "continent": "Oceania",
      },
      {
        "code": "KP",
        "country": "North Korea",
        "continent": "Asia",
      },
      {
        "code": "KR",
        "country": "South Korea",
        "continent": "Asia",
      },
      {
        "code": "KW",
        "country": "Kuwait",
        "continent": "Asia",
      },
      {
        "code": "KG",
        "country": "Kyrgyzstan",
        "continent": "Asia",
      },
      {
        "code": "LA",
        "country": "Lao",
        "continent": "Asia",
      },
      {
        "code": "LV",
        "country": "Latvia",
        "continent": "Europe",
      },
      {
        "code": "LB",
        "country": "Lebanon",
        "continent": "Asia",
      },
      {
        "code": "LS",
        "country": "Lesotho",
        "continent": "Africa",
      },
      {
        "code": "LR",
        "country": "Liberia",
        "continent": "Africa",
      },
      {
        "code": "LY",
        "country": "Libya",
        "continent": "Africa",
      },
      {
        "code": "LI",
        "country": "Liechtenstein",
        "continent": "Europe",
      },
      {
        "code": "LT",
        "country": "Lithuania",
        "continent": "Europe",
      },
      {
        "code": "LU",
        "country": "Luxembourg",
        "continent": "Europe",
      },
      {
        "code": "MO",
        "country": "Macao",
        "continent": "Asia",
      },
      {
        "code": "MG",
        "country": "Madagascar",
        "continent": "Africa",
      },
      {
        "code": "MW",
        "country": "Malawi",
        "continent": "Africa",
      },
      {
        "code": "MY",
        "country": "Malaysia",
        "continent": "Asia",
      },
      {
        "code": "MV",
        "country": "Maldives",
        "continent": "Asia",
      },
      {
        "code": "ML",
        "country": "Mali",
        "continent": "Africa",
      },
      {
        "code": "MT",
        "country": "Malta",
        "continent": "Europe",
      },
      {
        "code": "MH",
        "country": "Marshall Islands",
        "continent": "Oceania",
      },
      {
        "code": "MQ",
        "country": "Martinique",
        "continent": "North America",
      },
      {
        "code": "MR",
        "country": "Mauritania",
        "continent": "Africa",
      },
      {
        "code": "MU",
        "country": "Mauritius",
        "continent": "Africa",
      },
      {
        "code": "YT",
        "country": "Mayotte",
        "continent": "Africa",
      },
      {
        "code": "MX",
        "country": "Mexico",
        "continent": "North America",
      },
      {
        "code": "FM",
        "country": "Micronesia",
        "continent": "Oceania",
      },
      {
        "code": "MD",
        "country": "Moldova",
        "continent": "Europe",
      },
      {
        "code": "MC",
        "country": "Monaco",
        "continent": "Europe",
      },
      {
        "code": "MN",
        "country": "Mongolia",
        "continent": "Asia",
      },
      {
        "code": "ME",
        "country": "Montenegro",
        "continent": "Europe",
      },
      {
        "code": "MS",
        "country": "Montserrat",
        "continent": "North America",
      },
      {
        "code": "MA",
        "country": "Morocco",
        "continent": "Africa",
      },
      {
        "code": "MZ",
        "country": "Mozambique",
        "continent": "Africa",
      },
      {
        "code": "MM",
        "country": "Myanmar",
        "continent": "Asia",
      },
      {
        "code": "NA",
        "country": "Namibia",
        "continent": "Africa",
      },
      {
        "code": "NR",
        "country": "Nauru",
        "continent": "Oceania",
      },
      {
        "code": "NP",
        "country": "Nepal",
        "continent": "Asia",
      },
      {
        "code": "NL",
        "country": "Netherlands",
        "continent": "Europe",
      },
      {
        "code": "NC",
        "country": "New Caledonia",
        "continent": "Oceania",
      },
      {
        "code": "NZ",
        "country": "New Zealand",
        "continent": "Oceania",
      },
      {
        "code": "NI",
        "country": "Nicaragua",
        "continent": "North America",
      },
      {
        "code": "NE",
        "country": "Niger",
        "continent": "Africa",
      },
      {
        "code": "NG",
        "country": "Nigeria",
        "continent": "Africa",
      },
      {
        "code": "NU",
        "country": "Niue",
        "continent": "Oceania",
      },
      {
        "code": "NF",
        "country": "Norfolk Island",
        "continent": "Oceania",
      },
      {
        "code": "MK",
        "country": "Macedonia",
        "continent": "Europe",
      },
      {
        "code": "MP",
        "country": "Northern Mariana",
        "continent": "Oceania",
      },
      {
        "code": "NO",
        "country": "Norway",
        "continent": "Europe",
      },
      {
        "code": "OM",
        "country": "Oman",
        "continent": "Asia",
      },
      {
        "code": "PK",
        "country": "Pakistan",
        "continent": "Asia",
      },
      {
        "code": "PW",
        "country": "Palau",
        "continent": "Oceania",
      },
      {
        "code": "XK",
        "country": "Kosovo",
        "continent": "Europe",
      },
      {
        "code": "PS",
        "country": "Palestine",
        "continent": "Asia",
      },
      {
        "code": "PA",
        "country": "Panama",
        "continent": "North America",
      },
      {
        "code": "PG",
        "country": "Papua New Guinea",
        "continent": "Oceania",
      },
      {
        "code": "PY",
        "country": "Paraguay",
        "continent": "South America",
      },
      {
        "code": "PE",
        "country": "Peru",
        "continent": "South America",
      },
      {
        "code": "PH",
        "country": "Philippines",
        "continent": "Asia",
      },
      {
        "code": "PN",
        "country": "Pitcairn",
        "continent": "Oceania",
      },
      {
        "code": "PL",
        "country": "Poland",
        "continent": "Europe",
      },
      {
        "code": "PT",
        "country": "Portugal",
        "continent": "Europe",
      },
      {
        "code": "PR",
        "country": "Puerto Rico",
        "continent": "North America",
      },
      {
        "code": "QA",
        "country": "Qatar",
        "continent": "Asia",
      },
      {
        "code": "RO",
        "country": "Romania",
        "continent": "Europe",
      },
      {
        "code": "RU",
        "country": "Russian",
        "continent": "Europe",
      },
      {
        "code": "RW",
        "country": "Rwanda",
        "continent": "Africa",
      },
      {
        "code": "RE",
        "country": "Réunion",
        "continent": "Africa",
      },
      {
        "code": "BL",
        "country": "Saint Barthélemy",
        "continent": "North America",
      },
      {
        "code": "SH",
        "country": "St Helena",
        "continent": "Africa",
      },
      {
        "code": "KN",
        "country": "St Kitts Nev",
        "continent": "North America",
      },
      {
        "code": "LC",
        "country": "Saint Lucia",
        "continent": "North America",
      },
      {
        "code": "MF",
        "country": "St Martin",
        "continent": "North America",
      },
      {
        "code": "PM",
        "country": "St Pier Mq",
        "continent": "North America",
      },
      {
        "code": "VC",
        "country": "St Vincent",
        "continent": "North America",
      },
      {
        "code": "WS",
        "country": "Samoa",
        "continent": "Oceania",
      },
      {
        "code": "SM",
        "country": "San Marino",
        "continent": "Europe",
      },
      {
        "code": "ST",
        "country": "Sao Tome Prn",
        "continent": "Africa",
      },
      {
        "code": "SA",
        "country": "Saudi Arabia",
        "continent": "Asia",
      },
      {
        "code": "SN",
        "country": "Senegal",
        "continent": "Africa",
      },
      {
        "code": "RS",
        "country": "Serbia",
        "continent": "Europe",
      },
      {
        "code": "SC",
        "country": "Seychelles",
        "continent": "Africa",
      },
      {
        "code": "SL",
        "country": "Sierra Leone",
        "continent": "Africa",
      },
      {
        "code": "SG",
        "country": "Singapore",
        "continent": "Asia",
      },
      {
        "code": "SX",
        "country": "Sint Maarten",
        "continent": "North America",
      },
      {
        "code": "SK",
        "country": "Slovakia",
        "continent": "Europe",
      },
      {
        "code": "SI",
        "country": "Slovenia",
        "continent": "Europe",
      },
      {
        "code": "SB",
        "country": "Solomon Islands",
        "continent": "Oceania",
      },
      {
        "code": "SO",
        "country": "Somalia",
        "continent": "Africa",
      },
      {
        "code": "ZA",
        "country": "South Africa",
        "continent": "Africa",
      },
      {
        "code": "GS",
        "country": "Georgia Sandwich Isl",
        "continent": "Antartica",
      },
      {
        "code": "SS",
        "country": "South Sudan",
        "continent": "Africa",
      },
      {
        "code": "ES",
        "country": "Spain",
        "continent": "Europe",
      },
      {
        "code": "LK",
        "country": "Sri Lanka",
        "continent": "Asia",
      },
      {
        "code": "SD",
        "country": "Sudan",
        "continent": "Africa",
      },
      {
        "code": "SR",
        "country": "Suriname",
        "continent": "South America",
      },
      {
        "code": "SJ",
        "country": "Svalbard Jan Mayen",
        "continent": "Europe",
      },
      {
        "code": "SE",
        "country": "Sweden",
        "continent": "Europe",
      },
      {
        "code": "CH",
        "country": "Switzerland",
        "continent": "Europe",
      },
      {
        "code": "SY",
        "country": "Syrian",
        "continent": "Asia",
      },
      {
        "code": "TW",
        "country": "Taiwan",
        "continent": "Asia",
      },
      {
        "code": "TJ",
        "country": "Tajikistan",
        "continent": "Asia",
      },
      {
        "code": "TZ",
        "country": "Tanzania",
        "continent": "Africa",
      },
      {
        "code": "TH",
        "country": "Thailand",
        "continent": "Asia",
      },
      {
        "code": "TL",
        "country": "Timor-Leste",
        "continent": "Asia",
      },
      {
        "code": "TG",
        "country": "Togo",
        "continent": "Africa",
      },
      {
        "code": "TK",
        "country": "Tokelau",
        "continent": "Oceania",
      },
      {
        "code": "TO",
        "country": "Tonga",
        "continent": "Oceania",
      },
      {
        "code": "TT",
        "country": "Trinidad and Tobago",
        "continent": "North America",
      },
      {
        "code": "TN",
        "country": "Tunisia",
        "continent": "Africa",
      },
      {
        "code": "TR",
        "country": "Turkey",
        "continent": "Europe",
      },
      {
        "code": "TM",
        "country": "Turkmenistan",
        "continent": "Asia",
      },
      {
        "code": "TC",
        "country": "Turks Caicos Isl",
        "continent": "North America",
      },
      {
        "code": "TV",
        "country": "Tuvalu",
        "continent": "Oceania",
      },
      {
        "code": "UG",
        "country": "Uganda",
        "continent": "Africa",
      },
      {
        "code": "UA",
        "country": "Ukraine",
        "continent": "Europe",
      },
      {
        "code": "AE",
        "country": "Emirates",
        "continent": "Asia",
      },
      {
        "code": "GB",
        "country": "United Kingdom",
        "continent": "Europe",
      },
      {
        "code": "UM",
        "country": "United States MOI",
        "continent": "Oceania",
      },
      {
        "code": "US",
        "country": "United States",
        "continent": "North America",
      },
      {
        "code": "UY",
        "country": "Uruguay",
        "continent": "South America",
      },
      {
        "code": "UZ",
        "country": "Uzbekistan",
        "continent": "Asia",
      },
      {
        "code": "VU",
        "country": "Vanuatu",
        "continent": "Oceania",
      },
      {
        "code": "VE",
        "country": "Venezuela",
        "continent": "South America",
      },
      {
        "code": "VN",
        "country": "Viet Nam",
        "continent": "Asia",
      },
      {
        "code": "VG",
        "country": "Virgin Isl (UK)",
        "continent": "North America",
      },
      {
        "code": "VI",
        "country": "Virgin Isl (US)",
        "continent": "North America",
      },
      {
        "code": "WF",
        "country": "Wallis and Futuna",
        "continent": "Oceania",
      },
      {
        "code": "EH",
        "country": "Western Sahara",
        "continent": "Africa",
      },
      {
        "code": "YE",
        "country": "Yemen",
        "continent": "Asia",
      },
      {
        "code": "ZM",
        "country": "Zambia",
        "continent": "Africa",
      },
      {
        "code": "ZW",
        "country": "Zimbabwe",
        "continent": "Africa",
      }
  ],

  shYY: [
      { value: 1300, label: 1300 },
      { value: 1301, label: 1301 },
      { value: 1302, label: 1302 },
      { value: 1303, label: 1303 },
      { value: 1304, label: 1304 },
      { value: 1305, label: 1305 },
      { value: 1306, label: 1306 },
      { value: 1307, label: 1307 },
      { value: 1308, label: 1308 },
      { value: 1309, label: 1309 },
      { value: 1310, label: 1310 },
      { value: 1311, label: 1311 },
      { value: 1312, label: 1312 },
      { value: 1313, label: 1313 },
      { value: 1314, label: 1314 },
      { value: 1315, label: 1315 },
      { value: 1316, label: 1316 },
      { value: 1317, label: 1317 },
      { value: 1318, label: 1318 },
      { value: 1319, label: 1319 },
      { value: 1320, label: 1320 },
      { value: 1321, label: 1321 },
      { value: 1322, label: 1322 },
      { value: 1323, label: 1323 },
      { value: 1324, label: 1324 },
      { value: 1325, label: 1325 },
      { value: 1326, label: 1326 },
      { value: 1327, label: 1327 },
      { value: 1328, label: 1328 },
      { value: 1329, label: 1329 },
      { value: 1330, label: 1330 },
      { value: 1331, label: 1331 },
      { value: 1332, label: 1332 },
      { value: 1333, label: 1333 },
      { value: 1334, label: 1334 },
      { value: 1335, label: 1335 },
      { value: 1336, label: 1336 },
      { value: 1337, label: 1337 },
      { value: 1338, label: 1338 },
      { value: 1339, label: 1339 },
      { value: 1340, label: 1340 },
      { value: 1341, label: 1341 },
      { value: 1342, label: 1342 },
      { value: 1343, label: 1343 },
      { value: 1344, label: 1344 },
      { value: 1345, label: 1345 },
      { value: 1346, label: 1346 },
      { value: 1347, label: 1347 },
      { value: 1348, label: 1348 },
      { value: 1349, label: 1349 },
      { value: 1350, label: 1350 },
      { value: 1351, label: 1351 },
      { value: 1352, label: 1352 },
      { value: 1353, label: 1353 },
      { value: 1354, label: 1354 },
      { value: 1355, label: 1355 },
      { value: 1356, label: 1356 },
      { value: 1357, label: 1357 },
      { value: 1358, label: 1358 },
      { value: 1359, label: 1359 },
      { value: 1360, label: 1360 },
      { value: 1361, label: 1361 },
      { value: 1362, label: 1362 },
      { value: 1363, label: 1363 },
      { value: 1364, label: 1364 },
      { value: 1365, label: 1365 },
      { value: 1366, label: 1366 },
      { value: 1367, label: 1367 },
      { value: 1368, label: 1368 },
      { value: 1369, label: 1369 },
      { value: 1370, label: 1370 },
      { value: 1371, label: 1371 },
      { value: 1372, label: 1372 },
      { value: 1373, label: 1373 },
      { value: 1374, label: 1374 },
      { value: 1375, label: 1375 },
      { value: 1376, label: 1376 },
      { value: 1377, label: 1377 },
      { value: 1378, label: 1378 },
      { value: 1379, label: 1379 },
      { value: 1380, label: 1380 },
      { value: 1381, label: 1381 },
      { value: 1382, label: 1382 },
      { value: 1383, label: 1383 },
      { value: 1384, label: 1384 },
      { value: 1385, label: 1385 },
      { value: 1386, label: 1386 },
      { value: 1387, label: 1387 },
      { value: 1388, label: 1388 },
      { value: 1389, label: 1389 },
      { value: 1390, label: 1390 },
      { value: 1391, label: 1391 },
      { value: 1392, label: 1392 },
      { value: 1393, label: 1393 },
      { value: 1394, label: 1394 },
      { value: 1395, label: 1395 },
      { value: 1396, label: 1396 },
      { value: 1397, label: 1397 },
      { value: 1398, label: 1398 },
      { value: 1399, label: 1399 },
      { value: 1400, label: 1400 },
      { value: 1401, label: 1401 },
      { value: 1402, label: 1402 },
      { value: 1403, label: 1403 },
      { value: 1404, label: 1404 },
      { value: 1405, label: 1405 },
  ],
  mlYY: [
      { value: 1900, label: 1900 },
      { value: 1901, label: 1901 },
      { value: 1902, label: 1902 },
      { value: 1903, label: 1903 },
      { value: 1904, label: 1904 },
      { value: 1905, label: 1905 },
      { value: 1906, label: 1906 },
      { value: 1907, label: 1907 },
      { value: 1908, label: 1908 },
      { value: 1909, label: 1909 },
      { value: 1910, label: 1910 },
      { value: 1911, label: 1911 },
      { value: 1912, label: 1912 },
      { value: 1913, label: 1913 },
      { value: 1914, label: 1914 },
      { value: 1915, label: 1915 },
      { value: 1916, label: 1916 },
      { value: 1917, label: 1917 },
      { value: 1918, label: 1918 },
      { value: 1919, label: 1919 },
      { value: 1920, label: 1920 },
      { value: 1921, label: 1921 },
      { value: 1922, label: 1922 },
      { value: 1923, label: 1923 },
      { value: 1924, label: 1924 },
      { value: 1925, label: 1925 },
      { value: 1926, label: 1926 },
      { value: 1927, label: 1927 },
      { value: 1928, label: 1928 },
      { value: 1929, label: 1929 },
      { value: 1930, label: 1930 },
      { value: 1931, label: 1931 },
      { value: 1932, label: 1932 },
      { value: 1933, label: 1933 },
      { value: 1934, label: 1934 },
      { value: 1935, label: 1935 },
      { value: 1936, label: 1936 },
      { value: 1937, label: 1937 },
      { value: 1938, label: 1938 },
      { value: 1939, label: 1939 },
      { value: 1940, label: 1940 },
      { value: 1941, label: 1941 },
      { value: 1942, label: 1942 },
      { value: 1943, label: 1943 },
      { value: 1944, label: 1944 },
      { value: 1945, label: 1945 },
      { value: 1946, label: 1946 },
      { value: 1947, label: 1947 },
      { value: 1948, label: 1948 },
      { value: 1949, label: 1949 },
      { value: 1950, label: 1950 },
      { value: 1951, label: 1951 },
      { value: 1952, label: 1952 },
      { value: 1953, label: 1953 },
      { value: 1954, label: 1954 },
      { value: 1955, label: 1955 },
      { value: 1956, label: 1956 },
      { value: 1957, label: 1957 },
      { value: 1958, label: 1958 },
      { value: 1959, label: 1959 },
      { value: 1960, label: 1960 },
      { value: 1961, label: 1961 },
      { value: 1962, label: 1962 },
      { value: 1963, label: 1963 },
      { value: 1964, label: 1964 },
      { value: 1965, label: 1965 },
      { value: 1966, label: 1966 },
      { value: 1967, label: 1967 },
      { value: 1968, label: 1968 },
      { value: 1969, label: 1969 },
      { value: 1970, label: 1970 },
      { value: 1971, label: 1971 },
      { value: 1972, label: 1972 },
      { value: 1973, label: 1973 },
      { value: 1974, label: 1974 },
      { value: 1975, label: 1975 },
      { value: 1976, label: 1976 },
      { value: 1977, label: 1977 },
      { value: 1978, label: 1978 },
      { value: 1979, label: 1979 },
      { value: 1980, label: 1980 },
      { value: 1981, label: 1981 },
      { value: 1982, label: 1982 },
      { value: 1983, label: 1983 },
      { value: 1984, label: 1984 },
      { value: 1985, label: 1985 },
      { value: 1986, label: 1986 },
      { value: 1987, label: 1987 },
      { value: 1988, label: 1988 },
      { value: 1989, label: 1989 },
      { value: 1990, label: 1990 },
      { value: 1991, label: 1991 },
      { value: 1992, label: 1992 },
      { value: 1993, label: 1993 },
      { value: 1994, label: 1994 },
      { value: 1995, label: 1995 },
      { value: 1996, label: 1996 },
      { value: 1997, label: 1997 },
      { value: 1998, label: 1998 },
      { value: 1999, label: 1999 },
      { value: 2000, label: 2000 },
      { value: 2001, label: 2001 },
      { value: 2002, label: 2002 },
      { value: 2003, label: 2003 },
      { value: 2004, label: 2004 },
      { value: 2005, label: 2005 },
      { value: 2006, label: 2006 },
      { value: 2007, label: 2007 },
      { value: 2008, label: 2008 },
      { value: 2009, label: 2009 },
      { value: 2010, label: 2010 },
      { value: 2011, label: 2011 },
      { value: 2012, label: 2012 },
      { value: 2013, label: 2013 },
      { value: 2014, label: 2014 },
      { value: 2015, label: 2015 },
      { value: 2016, label: 2016 },
      { value: 2017, label: 2017 },
      { value: 2018, label: 2018 },
      { value: 2019, label: 2019 },
      { value: 2020, label: 2020 },
      { value: 2021, label: 2021 },
      { value: 2022, label: 2022 },
      { value: 2023, label: 2023 },
      { value: 2024, label: 2024 },
      { value: 2025, label: 2025 },
  ],
  MM: [
      { value: 1, label: '01' },
      { value: 2, label: '02' },
      { value: 3, label: '03' },
      { value: 4, label: '04' },
      { value: 5, label: '05' },
      { value: 6, label: '06' },
      { value: 7, label: '07' },
      { value: 8, label: '08' },
      { value: 9, label: '09' },
      { value: 10, label: '10' },
      { value: 11, label: '11' },
      { value: 12, label: '12' }
  ],
  DD: [
      { value: 1, label: '01' },
      { value: 2, label: '02' },
      { value: 3, label: '03' },
      { value: 4, label: '04' },
      { value: 5, label: '05' },
      { value: 6, label: '06' },
      { value: 7, label: '07' },
      { value: 8, label: '08' },
      { value: 9, label: '09' },
      { value: 10, label: '10' },
      { value: 11, label: '11' },
      { value: 12, label: '12' },
      { value: 13, label: '13' },
      { value: 14, label: '14' },
      { value: 15, label: '15' },
      { value: 16, label: '16' },
      { value: 17, label: '17' },
      { value: 18, label: '18' },
      { value: 19, label: '19' },
      { value: 20, label: '20' },
      { value: 21, label: '21' },
      { value: 22, label: '22' },
      { value: 23, label: '23' },
      { value: 24, label: '24' },
      { value: 25, label: '25' },
      { value: 26, label: '26' },
      { value: 27, label: '27' },
      { value: 28, label: '28' },
      { value: 29, label: '29' },
      { value: 30, label: '30' },
      { value: 31, label: '31' }
  ]

}