const config = {
  siteName:'ShiningPage',

  googleAds: true,

  // serverURL: 'http://localhost:4200',
  serverURL: 'https://api.shiningpage.com',

  noIndexPages: [
    'login',
    'register',
    'contact',
    'dashboard',
    'tos',
    'privacy',
    'disclaimer',
    'projects',
    'ruby',
    'booking',
    'chatList',
    'notification',
    'page404',
    'reviews',
    'user'
  ],

  socialTopics: {
    instagram: "Instagram",
    youtube: "Youtube",
    facebook: "Facebook",
    twitter: "X",
    tiktok: "TikTok",
    linkedin: "Linkedin",
    telegram: "Telegram",
    traffic: "Traffic",
    discord: "Discord",
    snapchat: "Snapchat",
    twitch: "Twitch",
    spotify: "Spotify",
    // google: "Google",
    // review: "Review",
  },

  s: 825,
  NavH: 60,
  langArray: ['fa', 'en', 'ar', ''],
  //subNavH: 70,
  headerColor1: '#000000',
  headerColor2: '#5b5bff',
  totalBorder: '#9e5dff80',
  listRefreshQty: 9,
  listRefreshQtyBig: 50,
  listRefreshQtySmall: 10,
  adsSpace: 20,

  copyRightText: '2024 All Rights Reserved',
  sideBlackIcon: [4, 11],
  lightColors: [0, 4, 9, 10, 11, 12, 13, 14, 22, 25, 42, 54, ],
  designedByColors: [0, 2, 3, 4, 9, 10, 11, 12, 13, 14, 16, 22, 24, 25, 38, 41, 49, 52],
  colors: {
    C0: '#BAC4D4',
    C1: '#364CFF',
    C2: '#24b735',
    C3: '#FF9547',
    C4: '#ede557',
    C5: '#B246D4',
    C6: '#824400',
    C7: '#000000',
    C8: '#ff002e',
    C9: '#f8cb71',
    C10: '#fd90e0',
    C11: '#ffffff',
    C12: '#00ddff',
    C13: '#77787A',
    C14: '#D1A449',
    C15: '#00194c',
    C16: '#D8A9A4',
    C17: '#0c5b14',
    C18: '#FC0496',
    C19: '#ff34a3',
    C20: '#8F1657',
    C21: '#541a67',
    C22: '#BAC4D4',
    C23: '#CE0301',
    C24: '#d5cc95',
    C25: '#99E315',
    C26: '#555555',
    C27: '#1c9328',
    C28: '#601C3B',
    C29: '#B24C31',
    C30: '#1c9328',
    C31: '#D1A449',
    C32: '#D1A449',
    C33: '#555555',
    C34: '#364CFF',
    C35: '#00BFDD',
    C36: '#B246D4',
    C37: '#c40020',
    C38: '#D1A449',
    C39: '#ff34a3',
    C40: '#000000',
    C41: '#24b735',
    C42: '#F4D011',
    C43: '#602909',
    C44: '#af011e',
    C45: '#24b735',
    C46: '#B246D4',
    C47: '#259FB4',
    C48: '#F81550',
    C49: '#00b0cb',
    C50: '#835965',
    C51: '#1079B8',
    C52: '#9D8361',
    C53: '#000000',
    C54: '#FBD8D0',
    C55: '#9564F7',
    C56: '#D1A449',
    C57: '#721119',
    C58: '#af011e',

  },
  mapColors: {
    C0: '#9aa7ba',
    C1: '#364CFF',
    C2: '#24b735',
    C3: '#FF9547',
    C4: '#f4ef5f',
    C5: '#B246D4',
    C6: '#824400',
    C7: '#000000',
    C8: '#ff002e',
    C9: '#f8cb71',
    C10: '#fd90e0',
    C11: '#555555',
    C12: '#00ddff',
    C13: '#555555',
    C14: '#D1A449',
    C15: '#00194c',
    C16: '#D8A9A4',
    C17: '#0c5b14',
    C18: '#FC0496',
    C19: '#ff34a3',
    C20: '#8F1657',
    C21: '#541a67',
    C22: '#555555',
    C23: '#CE0301',
    C24: '#c40020',
    C25: '#99E315',
    C26: '#555555',
    C27: '#1c9328',
    C28: '#601C3B',
    C29: '#B24C31',
    C30: '#1c9328',
    C31: '#B97F15',
    C32: '#B97F15',
    C33: '#555555',
    C34: '#364CFF',
    C35: '#00b0cb',
    C36: '#B246D4',
    C37: '#c40020',
    C38: '#D1A449',
    C39: '#d42e89',
    C40: '#000000',
    C41: '#24b735',
    C42: '#fed400',
    C43: '#602909',
    C44: '#c40020',
    C45: '#24b735',
    C46: '#B246D4',
    C47: '#10879c',
    C48: '#F81550',
    C49: '#00b0cb',
    C50: '#B58B97',
    C51: '#1079B8',
    C52: '#876d4e',
    C53: '#000000',
    C54: '#ca8e81',
    C55: '#9564F7',
    C56: '#ab7e22',
    C57: '#721119',
    C58: '#c40020',

  },
  categories: [ // index مهم است و نباید حذف شود چون در جدول های مختلف دیتابیس ذخیره شده است
    { index: 10, title: 'beautyHealthWellness' },
    { index: 2, title: 'buildingServices' },
    { index: 8, title: 'cleaningServices' },
    { index: 1, title: 'foodStuffs' },
    // { index: 3, title: 'industrialToolsEquipment' },
    // { index: 4, title: 'carSparePartsAccessories' },
    // { index: 5, title: 'digitalProductsAccessories' },
    // { index: 6, title: 'goldJewelryOrnaments' },
    // { index: 7, title: 'clothing' },
    { index: 9, title: 'homeKitchenAppliances' },
    // { index: 11, title: 'booksStationery' },
    // { index: 12, title: 'gameEntertainment' },
    { index: 13, title: 'artHandicraft' },
    // { index: 14, title: 'officeSupplies' },
    { index: 15, title: 'sportsRecreationalEquipment' },
    // { index: 16, title: 'petsAccessories' },
    { index: 17, title: 'trainingServices' },
    { index: 18, title: 'other' }
  ],

  countryArr: [
      {
        "code": "AF",
        "country": "Afghanistan",
        "continent": "Asia",
      },
      {
        "code": "AX",
        "country": "Aland Islands",
        "continent": "Europe",
      },
      {
        "code": "AL",
        "country": "Albania",
        "continent": "Europe",
      },
      {
        "code": "DZ",
        "country": "Algeria",
        "continent": "Africa",
      },
      {
        "code": "AS",
        "country": "American Samoa",
        "continent": "Oceania",
      },
      {
        "code": "AD",
        "country": "Andorra",
        "continent": "Europe",
      },
      {
        "code": "AO",
        "country": "Angola",
        "continent": "Africa",
      },
      {
        "code": "AI",
        "country": "Anguilla",
        "continent": "North America",
      },
      {
        "code": "AQ",
        "country": "Antarctica",
        "continent": "Antartica",
      },
      {
        "code": "AG",
        "country": "Antigua and Barbuda",
        "continent": "North America",
      },
      {
        "code": "AR",
        "country": "Argentina",
        "continent": "South America",
      },
      {
        "code": "AM",
        "country": "Armenia",
        "continent": "Asia",
      },
      {
        "code": "AW",
        "country": "Aruba",
        "continent": "North America",
      },
      {
        "code": "AU",
        "country": "Australia",
        "continent": "Oceania",
      },
      {
        "code": "AT",
        "country": "Austria",
        "continent": "Europe",
      },
      {
        "code": "AZ",
        "country": "Azerbaijan",
        "continent": "Asia",
      },
      {
        "code": "BS",
        "country": "Bahamas",
        "continent": "North America",
      },
      {
        "code": "BH",
        "country": "Bahrain",
        "continent": "Asia",
      },
      {
        "code": "BD",
        "country": "Bangladesh",
        "continent": "Asia",
      },
      {
        "code": "BB",
        "country": "Barbados",
        "continent": "North America",
      },
      {
        "code": "BY",
        "country": "Belarus",
        "continent": "Europe",
      },
      {
        "code": "BE",
        "country": "Belgium",
        "continent": "Europe",
      },
      {
        "code": "BZ",
        "country": "Belize",
        "continent": "North America",
      },
      {
        "code": "BJ",
        "country": "Benin",
        "continent": "Africa",
      },
      {
        "code": "BM",
        "country": "Bermuda",
        "continent": "North America",
      },
      {
        "code": "BT",
        "country": "Bhutan",
        "continent": "Asia",
      },
      {
        "code": "BO",
        "country": "Bolivia",
        "continent": "South America",
      },
      {
        "code": "BQ",
        "country": "Bonaire/Eust",
        "continent": "North America",
      },
      {
        "code": "BA",
        "country": "Bosnia Herzg",
        "continent": "Europe",
      },
      {
        "code": "BW",
        "country": "Botswana",
        "continent": "Africa",
      },
      {
        "code": "BV",
        "country": "Bouvet Island",
        "continent": "Antartica",
      },
      {
        "code": "BR",
        "country": "Brazil",
        "continent": "South America",
      },
      {
        "code": "IO",
        "country": "Br Ind Oc Tr",
        "continent": "Asia",
      },
      {
        "code": "BN",
        "country": "Brunei",
        "continent": "Asia",
      },
      {
        "code": "BG",
        "country": "Bulgaria",
        "continent": "Europe",
      },
      {
        "code": "BF",
        "country": "Burkina Faso",
        "continent": "Africa",
      },
      {
        "code": "BI",
        "country": "Burundi",
        "continent": "Africa",
      },
      {
        "code": "CV",
        "country": "Cabo Verde",
        "continent": "Africa",
      },
      {
        "code": "KH",
        "country": "Cambodia",
        "continent": "Asia",
      },
      {
        "code": "CM",
        "country": "Cameroon",
        "continent": "Africa",
      },
      {
        "code": "CA",
        "country": "Canada",
        "continent": "North America",
      },
      {
        "code": "KY",
        "country": "Cayman Islands",
        "continent": "North America",
      },
      {
        "code": "CF",
        "country": "Central African",
        "continent": "Africa",
      },
      {
        "code": "TD",
        "country": "Chad",
        "continent": "Africa",
      },
      {
        "code": "CL",
        "country": "Chile",
        "continent": "South America",
      },
      {
        "code": "CN",
        "country": "China",
        "continent": "Asia",
      },
      {
        "code": "CX",
        "country": "Christmas Island",
        "continent": "Asia",
      },
      {
        "code": "CC",
        "country": "Cocos Islands",
        "continent": "Asia",
      },
      {
        "code": "CO",
        "country": "Colombia",
        "continent": "South America",
      },
      {
        "code": "KM",
        "country": "Comoros",
        "continent": "Africa",
      },
      {
        "code": "CG",
        "country": "Congo",
        "continent": "Africa",
      },
      {
        "code": "CD",
        "country": "Congo",
        "continent": "Africa",
      },
      {
        "code": "CK",
        "country": "Cook Islands",
        "continent": "Oceania",
      },
      {
        "code": "CR",
        "country": "Costa Rica",
        "continent": "North America",
      },
      {
        "code": "HR",
        "country": "Croatia",
        "continent": "Europe",
      },
      {
        "code": "CU",
        "country": "Cuba",
        "continent": "North America",
      },
      {
        "code": "CW",
        "country": "Curaçao",
        "continent": "North America",
      },
      {
        "code": "CY",
        "country": "Cyprus",
        "continent": "Asia",
      },
      {
        "code": "CZ",
        "country": "Czechia",
        "continent": "Europe",
      },
      {
        "code": "CI",
        "country": "Côte d'Ivoire",
        "continent": "Africa",
      },
      {
        "code": "DK",
        "country": "Denmark",
        "continent": "Europe",
      },
      {
        "code": "DJ",
        "country": "Djibouti",
        "continent": "Africa",
      },
      {
        "code": "DM",
        "country": "Dominica",
        "continent": "North America",
      },
      {
        "code": "DO",
        "country": "Dominican",
        "continent": "North America",
      },
      {
        "code": "EC",
        "country": "Ecuador",
        "continent": "South America",
      },
      {
        "code": "EG",
        "country": "Egypt",
        "continent": "Africa",
      },
      {
        "code": "SV",
        "country": "El Salvador",
        "continent": "North America",
      },
      {
        "code": "GQ",
        "country": "Equatorial Guinea",
        "continent": "Africa",
      },
      {
        "code": "ER",
        "country": "Eritrea",
        "continent": "Africa",
      },
      {
        "code": "EE",
        "country": "Estonia",
        "continent": "Europe",
      },
      {
        "code": "SZ",
        "country": "Eswatini",
        "continent": "Africa",
      },
      {
        "code": "ET",
        "country": "Ethiopia",
        "continent": "Africa",
      },
      {
        "code": "FK",
        "country": "Falkland Islands",
        "continent": "South America",
      },
      {
        "code": "FO",
        "country": "Faroe Islands",
        "continent": "Europe",
      },
      {
        "code": "FJ",
        "country": "Fiji",
        "continent": "Oceania",
      },
      {
        "code": "FI",
        "country": "Finland",
        "continent": "Europe",
      },
      {
        "code": "FR",
        "country": "France",
        "continent": "Europe",
      },
      {
        "code": "GF",
        "country": "French Guiana",
        "continent": "South America",
      },
      {
        "code": "PF",
        "country": "French Polynesia",
        "continent": "Oceania",
      },
      {
        "code": "TF",
        "country": "French SRN TERR",
        "continent": "Antartica",
      },
      {
        "code": "GA",
        "country": "Gabon",
        "continent": "Africa",
      },
      {
        "code": "GM",
        "country": "Gambia",
        "continent": "Africa",
      },
      {
        "code": "GE",
        "country": "Georgia",
        "continent": "Asia",
      },
      {
        "code": "DE",
        "country": "Germany",
        "continent": "Europe",
      },
      {
        "code": "GH",
        "country": "Ghana",
        "continent": "Africa",
      },
      {
        "code": "GI",
        "country": "Gibraltar",
        "continent": "Europe",
      },
      {
        "code": "GR",
        "country": "Greece",
        "continent": "Europe",
      },
      {
        "code": "GL",
        "country": "Greenland",
        "continent": "North America",
      },
      {
        "code": "GD",
        "country": "Grenada",
        "continent": "North America",
      },
      {
        "code": "GP",
        "country": "Guadeloupe",
        "continent": "North America",
      },
      {
        "code": "GU",
        "country": "Guam",
        "continent": "Oceania",
      },
      {
        "code": "GT",
        "country": "Guatemala",
        "continent": "North America",
      },
      {
        "code": "GG",
        "country": "Guernsey",
        "continent": "Europe",
      },
      {
        "code": "GN",
        "country": "Guinea",
        "continent": "Africa",
      },
      {
        "code": "GW",
        "country": "Guinea-Bissau",
        "continent": "Africa",
      },
      {
        "code": "GY",
        "country": "Guyana",
        "continent": "South America",
      },
      {
        "code": "HT",
        "country": "Haiti",
        "continent": "North America",
      },
      {
        "code": "HM",
        "country": "Heard McDonald Isl",
        "continent": "Antartica",
      },
      {
        "code": "VA",
        "country": "Holy See",
        "continent": "Europe",
      },
      {
        "code": "HN",
        "country": "Honduras",
        "continent": "North America",
      },
      {
        "code": "HK",
        "country": "Hong Kong",
        "continent": "Asia",
      },
      {
        "code": "HU",
        "country": "Hungary",
        "continent": "Europe",
      },
      {
        "code": "IS",
        "country": "Iceland",
        "continent": "Europe",
      },
      {
        "code": "IN",
        "country": "India",
        "continent": "Asia",
      },
      {
        "code": "ID",
        "country": "Indonesia",
        "continent": "Asia",
      },
      {
        "code": "IR",
        "country": "Iran",
        "continent": "Asia",
      },
      {
        "code": "IQ",
        "country": "Iraq",
        "continent": "Asia",
      },
      {
        "code": "IE",
        "country": "Ireland",
        "continent": "Europe",
      },
      {
        "code": "IM",
        "country": "Isle of Man",
        "continent": "Europe",
      },
      {
        "code": "IL",
        "country": "Israel",
        "continent": "Asia",
      },
      {
        "code": "IT",
        "country": "Italy",
        "continent": "Europe",
      },
      {
        "code": "JM",
        "country": "Jamaica",
        "continent": "North America",
      },
      {
        "code": "JP",
        "country": "Japan",
        "continent": "Asia",
      },
      {
        "code": "JE",
        "country": "Jersey",
        "continent": "Europe",
      },
      {
        "code": "JO",
        "country": "Jordan",
        "continent": "Asia",
      },
      {
        "code": "KZ",
        "country": "Kazakhstan",
        "continent": "Asia",
      },
      {
        "code": "KE",
        "country": "Kenya",
        "continent": "Africa",
      },
      {
        "code": "KI",
        "country": "Kiribati",
        "continent": "Oceania",
      },
      {
        "code": "KP",
        "country": "North Korea",
        "continent": "Asia",
      },
      {
        "code": "KR",
        "country": "South Korea",
        "continent": "Asia",
      },
      {
        "code": "KW",
        "country": "Kuwait",
        "continent": "Asia",
      },
      {
        "code": "KG",
        "country": "Kyrgyzstan",
        "continent": "Asia",
      },
      {
        "code": "LA",
        "country": "Lao",
        "continent": "Asia",
      },
      {
        "code": "LV",
        "country": "Latvia",
        "continent": "Europe",
      },
      {
        "code": "LB",
        "country": "Lebanon",
        "continent": "Asia",
      },
      {
        "code": "LS",
        "country": "Lesotho",
        "continent": "Africa",
      },
      {
        "code": "LR",
        "country": "Liberia",
        "continent": "Africa",
      },
      {
        "code": "LY",
        "country": "Libya",
        "continent": "Africa",
      },
      {
        "code": "LI",
        "country": "Liechtenstein",
        "continent": "Europe",
      },
      {
        "code": "LT",
        "country": "Lithuania",
        "continent": "Europe",
      },
      {
        "code": "LU",
        "country": "Luxembourg",
        "continent": "Europe",
      },
      {
        "code": "MO",
        "country": "Macao",
        "continent": "Asia",
      },
      {
        "code": "MG",
        "country": "Madagascar",
        "continent": "Africa",
      },
      {
        "code": "MW",
        "country": "Malawi",
        "continent": "Africa",
      },
      {
        "code": "MY",
        "country": "Malaysia",
        "continent": "Asia",
      },
      {
        "code": "MV",
        "country": "Maldives",
        "continent": "Asia",
      },
      {
        "code": "ML",
        "country": "Mali",
        "continent": "Africa",
      },
      {
        "code": "MT",
        "country": "Malta",
        "continent": "Europe",
      },
      {
        "code": "MH",
        "country": "Marshall Islands",
        "continent": "Oceania",
      },
      {
        "code": "MQ",
        "country": "Martinique",
        "continent": "North America",
      },
      {
        "code": "MR",
        "country": "Mauritania",
        "continent": "Africa",
      },
      {
        "code": "MU",
        "country": "Mauritius",
        "continent": "Africa",
      },
      {
        "code": "YT",
        "country": "Mayotte",
        "continent": "Africa",
      },
      {
        "code": "MX",
        "country": "Mexico",
        "continent": "North America",
      },
      {
        "code": "FM",
        "country": "Micronesia",
        "continent": "Oceania",
      },
      {
        "code": "MD",
        "country": "Moldova",
        "continent": "Europe",
      },
      {
        "code": "MC",
        "country": "Monaco",
        "continent": "Europe",
      },
      {
        "code": "MN",
        "country": "Mongolia",
        "continent": "Asia",
      },
      {
        "code": "ME",
        "country": "Montenegro",
        "continent": "Europe",
      },
      {
        "code": "MS",
        "country": "Montserrat",
        "continent": "North America",
      },
      {
        "code": "MA",
        "country": "Morocco",
        "continent": "Africa",
      },
      {
        "code": "MZ",
        "country": "Mozambique",
        "continent": "Africa",
      },
      {
        "code": "MM",
        "country": "Myanmar",
        "continent": "Asia",
      },
      {
        "code": "NA",
        "country": "Namibia",
        "continent": "Africa",
      },
      {
        "code": "NR",
        "country": "Nauru",
        "continent": "Oceania",
      },
      {
        "code": "NP",
        "country": "Nepal",
        "continent": "Asia",
      },
      {
        "code": "NL",
        "country": "Netherlands",
        "continent": "Europe",
      },
      {
        "code": "NC",
        "country": "New Caledonia",
        "continent": "Oceania",
      },
      {
        "code": "NZ",
        "country": "New Zealand",
        "continent": "Oceania",
      },
      {
        "code": "NI",
        "country": "Nicaragua",
        "continent": "North America",
      },
      {
        "code": "NE",
        "country": "Niger",
        "continent": "Africa",
      },
      {
        "code": "NG",
        "country": "Nigeria",
        "continent": "Africa",
      },
      {
        "code": "NU",
        "country": "Niue",
        "continent": "Oceania",
      },
      {
        "code": "NF",
        "country": "Norfolk Island",
        "continent": "Oceania",
      },
      {
        "code": "MK",
        "country": "Macedonia",
        "continent": "Europe",
      },
      {
        "code": "MP",
        "country": "Northern Mariana",
        "continent": "Oceania",
      },
      {
        "code": "NO",
        "country": "Norway",
        "continent": "Europe",
      },
      {
        "code": "OM",
        "country": "Oman",
        "continent": "Asia",
      },
      {
        "code": "PK",
        "country": "Pakistan",
        "continent": "Asia",
      },
      {
        "code": "PW",
        "country": "Palau",
        "continent": "Oceania",
      },
      {
        "code": "XK",
        "country": "Kosovo",
        "continent": "Europe",
      },
      {
        "code": "PS",
        "country": "Palestine",
        "continent": "Asia",
      },
      {
        "code": "PA",
        "country": "Panama",
        "continent": "North America",
      },
      {
        "code": "PG",
        "country": "Papua New Guinea",
        "continent": "Oceania",
      },
      {
        "code": "PY",
        "country": "Paraguay",
        "continent": "South America",
      },
      {
        "code": "PE",
        "country": "Peru",
        "continent": "South America",
      },
      {
        "code": "PH",
        "country": "Philippines",
        "continent": "Asia",
      },
      {
        "code": "PN",
        "country": "Pitcairn",
        "continent": "Oceania",
      },
      {
        "code": "PL",
        "country": "Poland",
        "continent": "Europe",
      },
      {
        "code": "PT",
        "country": "Portugal",
        "continent": "Europe",
      },
      {
        "code": "PR",
        "country": "Puerto Rico",
        "continent": "North America",
      },
      {
        "code": "QA",
        "country": "Qatar",
        "continent": "Asia",
      },
      {
        "code": "RO",
        "country": "Romania",
        "continent": "Europe",
      },
      {
        "code": "RU",
        "country": "Russian",
        "continent": "Europe",
      },
      {
        "code": "RW",
        "country": "Rwanda",
        "continent": "Africa",
      },
      {
        "code": "RE",
        "country": "Réunion",
        "continent": "Africa",
      },
      {
        "code": "BL",
        "country": "Saint Barthélemy",
        "continent": "North America",
      },
      {
        "code": "SH",
        "country": "St Helena",
        "continent": "Africa",
      },
      {
        "code": "KN",
        "country": "St Kitts Nev",
        "continent": "North America",
      },
      {
        "code": "LC",
        "country": "Saint Lucia",
        "continent": "North America",
      },
      {
        "code": "MF",
        "country": "St Martin",
        "continent": "North America",
      },
      {
        "code": "PM",
        "country": "St Pier Mq",
        "continent": "North America",
      },
      {
        "code": "VC",
        "country": "St Vincent",
        "continent": "North America",
      },
      {
        "code": "WS",
        "country": "Samoa",
        "continent": "Oceania",
      },
      {
        "code": "SM",
        "country": "San Marino",
        "continent": "Europe",
      },
      {
        "code": "ST",
        "country": "Sao Tome Prn",
        "continent": "Africa",
      },
      {
        "code": "SA",
        "country": "Saudi Arabia",
        "continent": "Asia",
      },
      {
        "code": "SN",
        "country": "Senegal",
        "continent": "Africa",
      },
      {
        "code": "RS",
        "country": "Serbia",
        "continent": "Europe",
      },
      {
        "code": "SC",
        "country": "Seychelles",
        "continent": "Africa",
      },
      {
        "code": "SL",
        "country": "Sierra Leone",
        "continent": "Africa",
      },
      {
        "code": "SG",
        "country": "Singapore",
        "continent": "Asia",
      },
      {
        "code": "SX",
        "country": "Sint Maarten",
        "continent": "North America",
      },
      {
        "code": "SK",
        "country": "Slovakia",
        "continent": "Europe",
      },
      {
        "code": "SI",
        "country": "Slovenia",
        "continent": "Europe",
      },
      {
        "code": "SB",
        "country": "Solomon Islands",
        "continent": "Oceania",
      },
      {
        "code": "SO",
        "country": "Somalia",
        "continent": "Africa",
      },
      {
        "code": "ZA",
        "country": "South Africa",
        "continent": "Africa",
      },
      {
        "code": "GS",
        "country": "Georgia Sandwich Isl",
        "continent": "Antartica",
      },
      {
        "code": "SS",
        "country": "South Sudan",
        "continent": "Africa",
      },
      {
        "code": "ES",
        "country": "Spain",
        "continent": "Europe",
      },
      {
        "code": "LK",
        "country": "Sri Lanka",
        "continent": "Asia",
      },
      {
        "code": "SD",
        "country": "Sudan",
        "continent": "Africa",
      },
      {
        "code": "SR",
        "country": "Suriname",
        "continent": "South America",
      },
      {
        "code": "SJ",
        "country": "Svalbard Jan Mayen",
        "continent": "Europe",
      },
      {
        "code": "SE",
        "country": "Sweden",
        "continent": "Europe",
      },
      {
        "code": "CH",
        "country": "Switzerland",
        "continent": "Europe",
      },
      {
        "code": "SY",
        "country": "Syrian",
        "continent": "Asia",
      },
      {
        "code": "TW",
        "country": "Taiwan",
        "continent": "Asia",
      },
      {
        "code": "TJ",
        "country": "Tajikistan",
        "continent": "Asia",
      },
      {
        "code": "TZ",
        "country": "Tanzania",
        "continent": "Africa",
      },
      {
        "code": "TH",
        "country": "Thailand",
        "continent": "Asia",
      },
      {
        "code": "TL",
        "country": "Timor-Leste",
        "continent": "Asia",
      },
      {
        "code": "TG",
        "country": "Togo",
        "continent": "Africa",
      },
      {
        "code": "TK",
        "country": "Tokelau",
        "continent": "Oceania",
      },
      {
        "code": "TO",
        "country": "Tonga",
        "continent": "Oceania",
      },
      {
        "code": "TT",
        "country": "Trinidad and Tobago",
        "continent": "North America",
      },
      {
        "code": "TN",
        "country": "Tunisia",
        "continent": "Africa",
      },
      {
        "code": "TR",
        "country": "Turkey",
        "continent": "Europe",
      },
      {
        "code": "TM",
        "country": "Turkmenistan",
        "continent": "Asia",
      },
      {
        "code": "TC",
        "country": "Turks Caicos Isl",
        "continent": "North America",
      },
      {
        "code": "TV",
        "country": "Tuvalu",
        "continent": "Oceania",
      },
      {
        "code": "UG",
        "country": "Uganda",
        "continent": "Africa",
      },
      {
        "code": "UA",
        "country": "Ukraine",
        "continent": "Europe",
      },
      {
        "code": "AE",
        "country": "Emirates",
        "continent": "Asia",
      },
      {
        "code": "GB",
        "country": "United Kingdom",
        "continent": "Europe",
      },
      {
        "code": "UM",
        "country": "United States MOI",
        "continent": "Oceania",
      },
      {
        "code": "US",
        "country": "United States",
        "continent": "North America",
      },
      {
        "code": "UY",
        "country": "Uruguay",
        "continent": "South America",
      },
      {
        "code": "UZ",
        "country": "Uzbekistan",
        "continent": "Asia",
      },
      {
        "code": "VU",
        "country": "Vanuatu",
        "continent": "Oceania",
      },
      {
        "code": "VE",
        "country": "Venezuela",
        "continent": "South America",
      },
      {
        "code": "VN",
        "country": "Viet Nam",
        "continent": "Asia",
      },
      {
        "code": "VG",
        "country": "Virgin Isl (UK)",
        "continent": "North America",
      },
      {
        "code": "VI",
        "country": "Virgin Isl (US)",
        "continent": "North America",
      },
      {
        "code": "WF",
        "country": "Wallis and Futuna",
        "continent": "Oceania",
      },
      {
        "code": "EH",
        "country": "Western Sahara",
        "continent": "Africa",
      },
      {
        "code": "YE",
        "country": "Yemen",
        "continent": "Asia",
      },
      {
        "code": "ZM",
        "country": "Zambia",
        "continent": "Africa",
      },
      {
        "code": "ZW",
        "country": "Zimbabwe",
        "continent": "Africa",
      }
  ],

};

export const {
  siteName, googleAds, serverURL, noIndexPages, socialTopics, s, NavH, langArray,
  headerColor1, headerColor2, totalBorder, listRefreshQty, listRefreshQtyBig,
  listRefreshQtySmall, adsSpace, copyRightText, sideBlackIcon, lightColors, 
  designedByColors, colors, mapColors, categories, psyCard, countryArr, 
} = config;

export default config;